### ISSUE TITLE
Collections not found on Windows

### ISSUE THREAD

**Issue by dnndev** [DanWebb/jdown#4]
After upgrading to v.0.2.0 which resolved #2, I'm getting "Cannot read property `map` of undefined".  I have multiple folders in my `collections` folder: contributors, galleryImages, pastMeetings, and posts. 

On Windows, if I try iterating through any of them with `map` on any route in react-static's `static.config.js` I get the error. I do not get this error on the Mac. I have tried removing all routes, one at a time that include the iteration and I continue to get the error on the first encounter of `map` on a collection, regardless of the collection.

**Comment by dnndev** [comment]
If it helps, my `content` directory is in the project root and not in `/src`. My folder structure looks like:

```
/content
--/collections
----/contributors
----/galleryImages
----/pastMeetings
----/posts
------/post1.md
------/post2.md
--/home
--history.md
/src
--/containers
```

**Comment by DanWebb** [comment]
Thanks detailing this, I spun up a windows VM to test as I don't have a windows computer handy and managed to replicate the behaviour that I think must be causing your issue, seems like it's down to windows file path separators messing up the property names so you were likely doing something like `content.collection.map` where the `collection` property didn't exist because of this issue.

If you upgrade to 0.3.0 it should all be fixed now!

**Comment by dnndev** [comment]
Hi Dan,

I was able to test the new release (0.4.0) today and wanted to report back that it worked :) Thanks a ton for fixing it :)

Cheers,
Kelly
